---

extends:
  - airbnb
  - "plugin:jest/recommended"
  - "plugin:react/recommended"

parserOptions:
  ecmaFeatures:
    jsx: true

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

rules:
  import/no-unresolved: 0
  import/extensions: 0
  react/prop-types: 0
